### PR TITLE
Add Doppler descriptive installation guide in README

### PR DESCRIPTION
**Pull request by carlomigueldy**
Added descriptive Doppler installation instructions.

### CODE REVIEW

**Comment by angeljgomezc** [comment]
Is it possible to add Windows? I think tons of people still use that (like me hehe)

If you can't because you don't own a Windows computer, I'll do it later today

**Comment by angeljgomezc** [comment]
Also, should we separate the installation instructions from the `README.md`?

That way it's a bit less confusing? (Just a suggestion)

@with-heart @Dhaiwat10 @JoviDeCroock

**Comment by JoviDeCroock** [comment]
I'm personally a bit opposed to clogging the README with a potentially out-of-date installation that won't cover all OS'es. If we cover Mac and Win why wouldn't we add for instance Ubuntu. Hence my initial preference of just dropping the link where we trust the product to keep the instructions up to date.

**Comment by carlomigueldy** [comment]
> I'm personally a bit opposed to clogging the README with a potentially out-of-date installation that won't cover all OS'es. If we cover Mac and Win why wouldn't we add for instance Ubuntu. Hence my initial preference of just dropping the link where we trust the product to keep the instructions up to date.

Yeah I agree to this though.

**Review by frankTurtle — APPROVED** [review]
Doppler looks awesome! Thanks for showing me this 💪

LGTM 🤙🤙

**Comment by Dhaiwat10** [comment]
> Also, should we separate the installation instructions from the README.md?

Agreed. We should move this to `CONTRIBUTING.md`.

**Comment by carlomigueldy** [comment]
I'm going to extract it out into `CONTRIBUTING.md`, maybe tomorrow on weekend. My brain is a bit toast today lol.

**Comment by carlomigueldy** [comment]
Requesting for review @JoviDeCroock @Dhaiwat10 @angeljgomezc @frankTurtle

**Review by angeljgomezc — APPROVED** [review]

**Pull request merged**
