### PR TITLE
chore: add .yarnrc.yml 

### PR DESCRIPTION
**Pull request by G3root**

### CODE REVIEW

**Comment by with-heart** [comment]
Which version of `yarn` are you using? Seems like this will cause constant conflicts in `yarn.lock` format if we're not all on the same `major` version. 

I've never moved past v1 so I can see the conflict on my local: if I run `yarn` to install, `yarn.lock` looks like the version before your change.

Not sure what to do about that. Maybe I should finally upgrade `yarn`? Most of the projects I contribute to are still using v1 and I'm not sure what the difference is.

**Comment by G3root** [comment]
> Which version of `yarn` are you using? Seems like this will cause constant conflicts in `yarn.lock` format if we're not all on the same `major` version. 
> 
> I've never moved past v1 so I can see the conflict on my local: if I run `yarn` to install, `yarn.lock` looks like the version before your change.
> 
> Not sure what to do about that. Maybe I should finally upgrade `yarn`? Most of the projects I contribute to are still using v1 and I'm not sure what the difference is.

I mostly switch between version 1 and 2 based on the projects.  
I think it's better to upgrade, because it's now a monorepo and I think yarn 1 doesn't supports workspaces not sure.

**Comment by with-heart** [comment]
> I mostly switch between version 1 and 2 based on the projects. I think it's better to upgrade, because it's now a monorepo and I think yarn 1 doesn't supports workspaces not sure.

It does support workspaces, but I'm still interested in exploring that! 

Since this potentially affects most of the people working on the repo, would you mind opening an issue to propose that?

If you could include a link or two about how to upgrade + what the differences are between v1 and v2, I think that'd be very helpful!

**Comment by G3root** [comment]
> > I mostly switch between version 1 and 2 based on the projects. I think it's better to upgrade, because it's now a monorepo and I think yarn 1 doesn't supports workspaces not sure.
> 
> It does support workspaces, but I'm still interested in exploring that!
> 
> Since this potentially affects most of the people working on the repo, would you mind opening an issue to propose that?
> 
Most of the people working on this repo are using yarn 1, so I think it's relavant to close this PR.
What's your thoughts on this ?
> If you could include a link or two about how to upgrade + what the differences are between v1 and v2, I think that'd be very helpful!

This might be helpful https://spin.atomicobject.com/2021/02/17/switch-yarn-2/

**Pull request closed without merging**
