### PR TITLE
Fix sidebar layout

### PR DESCRIPTION
**Pull request by Dhaiwat10**
This PR positions the content of the inner pages correctly by re-factoring and adjusting margins in the `MainComponent`.

Without this fix, I wasn't able to style the new profile page properly. Let's merge this one before proceeding to work on #207.

### CODE REVIEW

**Comment by PBillingsby** [comment]
@Dhaiwat10 just checked this out on MacBook and iPhone and these changes seem to have affected the mobile responsiveness.

**Comment by Dhaiwat10** [comment]
@PBillingsby good catch. Will fix and let u know!

**Comment by Dhaiwat10** [comment]
@PBillingsby is it fixed now?

**Comment by PBillingsby** [comment]
LGTM. Pages are back to responsive
5B6F2E54-EBC8-4192-9CB7-29C71945A16F

**Pull request merged**
