### PR TITLE
Migrated Everything to Chakra UI

### PR DESCRIPTION
**Pull request by angeljgomezc**
Finished the migration from Styled Components to Chakra UI as assigned at: https://github.com/Developer-DAO/DAO-job-board/issues/20

### CODE REVIEW

**Comment by Dhaiwat10** [comment]
@angeljgomezc awesome, let's review this in tomorrow's group session we have planned on Discord?

**Comment by angeljgomezc** [comment]
> @angeljgomezc awesome, let's review this in tomorrow's group session we have planned on Discord?

No problem with that. I had planned of pushing a few extra things to finish the front-end before connecting to back-end

**Comment by Dhaiwat10** [comment]
@angeljgomezc the build is failing due to an error during `yarn build`. Could you have a look?

**Comment by angeljgomezc** [comment]
> @angeljgomezc the build is failing due to an error during `yarn build`. Could you have a look?

Hey mate! Can you send me a screenshot of Vercel's console? It's deploying fine on [my fork](https://dao-job-board-murex.vercel.app/)

**Comment by angeljgomezc** [comment]
> 
> 
> @angeljgomezc the build is failing due to an error during `yarn build`. Could you have a look?

Hey @Dhaiwat10! You can preview changes now - it should build with no issues. I had previously committed a change that didn't build + forgot it would also add up to this PR

**Pull request merged**
