### PR TITLE
Updated all Module path aliases

### PR DESCRIPTION
**Pull request by frankTurtle**
# What does it fix?
Solves #61 
No longer using `../../../../folder/lib` imports in the `client` folder

# Notes
For some reason the aliases don't work?

### CODE REVIEW

**Comment by G3root** [comment]
Absolute imports makes it easier to move files around and avoid messy import paths such as `../../../Component`.

Other than having multiple paths for different folders (such as `@components`, `@hooks`, etc...) , Using `@/*` or `~/*` works very well because it is short enough so there is no need to configure multiple paths and it differs from other dependency modules, so there is no confusion in what comes from `node_modules` and what is our source folder.

Example config for current structure.

```
// tsconfig.json
"compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["*"]
    }
  }
```

**Comment by carlomigueldy** [comment]
> Absolute imports makes it easier to move files around and avoid messy import paths such as `../../../Component`.
> 
> Other than having multiple paths for different folders (such as `@components`, `@hooks`, etc...) , Using `@/*` or `~/*` works very well because it is short enough so there is no need to configure multiple paths and it differs from other dependency modules, so there is no confusion in what comes from `node_modules` and what is our source folder.
> 
> Example config for current structure.
> 
> ```
> // tsconfig.json
> "compilerOptions": {
>     "baseUrl": ".",
>     "paths": {
>       "@/*": ["*"]
>     }
>   }
> ```

Yup let's go with this one @frankTurtle

**Comment by frankTurtle** [comment]
I'll get this pushed tomorrow, sorry for the delay!

**Comment by frankTurtle** [comment]
Give 'er a look-see @with-heart && @carlomigueldy

**Review by angeljgomezc — APPROVED** [review]

**Pull request merged**
