### PR TITLE
Docker setup

### PR DESCRIPTION
**Pull request by daviddale**
Readme for setting up Supabase to run locally with Docker.

### CODE REVIEW

**Review by carlomigueldy — APPROVED** [review]
Awesome stuff! 🔥

**Comment by PBillingsby** [comment]
@carlomigueldy @daviddale wait why was this merged? It wasn’t working properly right??

**Comment by carlomigueldy** [comment]
> @carlomigueldy @daviddale wait why was this merged? It wasn’t working properly right??

Whoops! Mb. 😅 

Though it felt safe to merge, lol because it was only just a `DOCKER.md` file that's added so it isn't breaking anything

**Comment by PBillingsby** [comment]
@carlomigueldy No worries! Just thought someone might try this set up and get errors

**Comment by daviddale** [comment]
Hoping to get it corrected this week and have a working version. Thanks

**Pull request merged**
