### PR TITLE
Add `nonce` attribute

### PR DESCRIPTION
**Pull request by carlomigueldy**
Since we're gonna be interacting with a smart contract for the gigs as per discussions around it and mentioned in this PR https://github.com/Developer-DAO/DAO-job-board/pull/64#discussion_r753398890

Thought we'd just add the `nonce` attribute now together with the wallet sign in :)

### CODE REVIEW

**Comment by carlomigueldy** [comment]
Hey @JoviDeCroock is varchar a good data type for `nonce`?

**Comment by JoviDeCroock** [comment]
> Hey @JoviDeCroock is varchar a good data type for `nonce`?

Depends on what we want as the value, currently it's a number but we could also go for a uuidv4 if y'all prefer

**Comment by carlomigueldy** [comment]
> > Hey @JoviDeCroock is varchar a good data type for `nonce`?
> 
> Depends on what we want as the value, currently it's a number but we could also go for a uuidv4 if y'all prefer

`uuidv4` would be cool

**Comment by carlomigueldy** [comment]
Changed to `uuid` data type @JoviDeCroock

**Pull request merged**
