### PR TITLE
Add dynamic options for select element for position and title.

### PR DESCRIPTION
**Pull request by PBillingsby**
## What
Refactoring select elements to map over array of values.

## Why
Add ability to easily add new values to select box without explicitly adding new HTML.

### CODE REVIEW

**Review by carlomigueldy — COMMENTED** [review]
Awesome thanks for the PR! @PBillingsby 

Can you add a comment somewhere that indicates that it needs to fetch the actual data coming from the database

Maybe something like a todo annotation jsDoc
```js
/**
  *  @todo comment here
  */
```

**Comment by PBillingsby** [comment]
@carlomigueldy Done.

**Comment by angeljgomezc** [comment]
Hey @PBillingsby! This is a great addition and you're totally right! I'm working on a new slightly different form for jobs so I'll wait until that's merged before merging this.

**Review by angeljgomezc — APPROVED** [review]
To be merged after #78

**Comment by carlomigueldy** [comment]
Need you to resolve the merge conflicts then we can merge this in @PBillingsby 🙌

**Comment by PBillingsby** [comment]
Closing as I need to reset environment. Will reopen soon.

**Pull request closed without merging**
